"""Change recording fields to String

Revision ID: 0310497184ba
Revises: b1a5d80f1906
Create Date: 2025-06-04 17:50:19.131046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '0310497184ba'
down_revision: Union[str, None] = 'b1a5d80f1906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a', 'focus_recording',
               existing_type=mssql.BIT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('form_a_requirements', 'prior_clearance',
               existing_type=mssql.BIT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('form_a_requirements', 'need_jbs_clearance1',
               existing_type=mssql.BIT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a_requirements', 'need_jbs_clearance1',
               existing_type=sa.String(length=255),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('form_a_requirements', 'prior_clearance',
               existing_type=sa.String(length=255),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('form_a', 'focus_recording',
               existing_type=sa.String(),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
